//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cart
    {
        public int IdCart { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdMember { get; set; }
        public Nullable<int> IdCartStatus { get; set; }
    
        public virtual Tbl_Cart_Status Tbl_Cart_Status { get; set; }
        public virtual Tbl_Members Tbl_Members { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
